# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
